// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Models;

public partial class bible_verses
{
    public int id { get; set; }

    public string verse { get; set; }

    public string chapter { get; set; }

    public DateOnly? date { get; set; }

    public bool? archive { get; set; }
}