// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Models;

public partial class information_system_cluster
{
    public int id { get; set; }

    public string cluster_name { get; set; }

    public byte[] icon { get; set; }

    public bool? active { get; set; }

    public virtual ICollection<information_system> information_system { get; set; } = new List<information_system>();
}