// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ePortal.WebAPI.Models;

public partial class pgas_eportal_v2Context : DbContext
{
    public pgas_eportal_v2Context(DbContextOptions<pgas_eportal_v2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<bible_verses> bible_verses { get; set; }

    public virtual DbSet<information_system> information_system { get; set; }

    public virtual DbSet<information_system_cluster> information_system_cluster { get; set; }

    public virtual DbSet<praise_message> praise_message { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<bible_verses>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__daily_wo__3213E83F71C8AD45");

            entity.Property(e => e.chapter).HasMaxLength(255);
            entity.Property(e => e.verse).HasMaxLength(255);
        });

        modelBuilder.Entity<information_system>(entity =>
        {
            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.abbreviation).HasMaxLength(255);
            entity.Property(e => e.information_system_name).HasMaxLength(255);
            entity.Property(e => e.link).HasMaxLength(255);

            entity.HasOne(d => d.information_system_cluster).WithMany(p => p.information_system)
                .HasForeignKey(d => d.information_system_cluster_id)
                .HasConstraintName("FK_information_system_information_system_cluster");
        });

        modelBuilder.Entity<information_system_cluster>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__informat__3213E83F59A53570");

            entity.Property(e => e.cluster_name).HasMaxLength(255);
        });

        modelBuilder.Entity<praise_message>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__praise_m__3213E83FCA56F543");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.date).HasColumnType("datetime");
            entity.Property(e => e.from)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.message).IsUnicode(false);
            entity.Property(e => e.to)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}