// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Models;

public partial class praise_message
{
    public int id { get; set; }

    public string from { get; set; }

    public string to { get; set; }

    public string message { get; set; }

    public DateTime? date { get; set; }

    public bool? archive { get; set; }
}