// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class emergency_hotline
{
    public int id { get; set; }

    public int office_id { get; set; }

    public int line_id { get; set; }

    public string area { get; set; }

    public string mobile_number { get; set; }

    public virtual emergency_hotline_line line { get; set; }

    public virtual emergency_hotline_office office { get; set; }
}