// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class emergency_hotline_line
{
    public int id { get; set; }

    public string line { get; set; }

    public virtual ICollection<emergency_hotline> emergency_hotline { get; set; } = new List<emergency_hotline>();
}