// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class ip_phone_directory
{
    public int id { get; set; }

    public int office_id { get; set; }

    public int line_id { get; set; }

    public int area_id { get; set; }

    public string office_area { get; set; }

    public string line_number { get; set; }

    public virtual ip_phone_directory_area area { get; set; }

    public virtual ip_phone_directory_line line { get; set; }

    public virtual ip_phone_directory_office office { get; set; }
}