// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class m_vwGetAllEmployee_Minified
{
    public long eid { get; set; }

    public string SwipeId { get; set; }

    public string EmpName { get; set; }

    public string EmpFullName { get; set; }

    public int? Department { get; set; }

    public string OfficeAbbr { get; set; }

    public string OfficeName { get; set; }

    public string Position { get; set; }

    public int? SG { get; set; }

    public byte? employmentstatus_id { get; set; }

    public string Status { get; set; }

    public int isShifty { get; set; }

    public bool? isactive { get; set; }
}