// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class v_external_link
{
    public string Parent_List_Name { get; set; }

    public string Parent_List_Icon { get; set; }

    public string Parent_List_Link { get; set; }

    public int? Parent_List_Order { get; set; }

    public DateOnly? Parent_List_Date_Created { get; set; }

    public string Child_List_Name { get; set; }

    public string Child_List_Link { get; set; }

    public string Child_List_Icon { get; set; }

    public int? Child_List_Order { get; set; }

    public DateOnly? Child_List_Date_Created { get; set; }
}