// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class v_ip_phone_directory
{
    public string Line { get; set; }

    public string Area { get; set; }

    public string Office { get; set; }

    public string Office_Abbreviation { get; set; }

    public string Office_Area { get; set; }

    public string Line_Number { get; set; }
}