// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class carousel_image
{
    public string file_name { get; set; }
    public DateTime upload_date { get; set; }
}