// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class external_link_child
{
    public int id { get; set; }

    public int? parent_id { get; set; }

    public string name { get; set; }

    public string link { get; set; }

    public string icon { get; set; }

    public int? order { get; set; }

    public DateOnly? date_created { get; set; }

    public bool? active { get; set; }

    public virtual external_link_parent parent { get; set; }
}