// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class information_system
{
    public int id { get; set; }

    public int? information_system_cluster_id { get; set; }

    public string name { get; set; }

    public string abbreviation { get; set; }

    public string icon { get; set; }

    public string link { get; set; }

    public string platform { get; set; }

    public DateOnly? date_created { get; set; }

    public bool? active { get; set; }

    public virtual information_system_cluster information_system_cluster { get; set; }
}