// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class ip_phone_directory_area
{
    public int id { get; set; }

    public string area { get; set; }

    public virtual ICollection<ip_phone_directory> ip_phone_directory { get; set; } = new List<ip_phone_directory>();
}