// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ePortal.WebAPI.Entities;

public partial class praise_message
{
    public int id { get; set; }
    public long from_eid { get; set; }
    public long to_eid { get; set; }
    public string message { get; set; }
    public int stars { get; set; }
    public DateTime? date { get; set; }
    public bool? archive { get; set; }
}